### ISSUE TITLE
EVM Faucet

### ISSUE THREAD

**Issue by joroshiba** [astriaorg/dev-cluster#10]
Create a faucet setup for devnet EVM.

Gives the ability to transfer tokens to an account, with a mechanism in which we are responsible for/has limits.

**Comment by jbowen93** [comment]
This is a good thing to talk to Bware labs about

**Comment by joroshiba** [comment]
Talking to bware tomorrow morning, hopefully gain some good context here.

**Comment by steezeburger** [comment]
Ended up going with a fork and skin of chainflag's faucet server
https://github.com/astriaorg/eth-faucet
