### ISSUE TITLE
Customizable EVM deployment

### ISSUE THREAD

**Issue by steezeburger** [astriaorg/dev-cluster#13]
Currently my account hash is hardcoded into the geth configs.

It should be possible to use your own local account for the dev-cluster. This will require a template to get the user's hash to work with kustomization

**Comment by joroshiba** [comment]
related to #19

**Comment by joroshiba** [comment]
PR #22 updates the configuration here so it's at least clear how to get this information, and provides a private key to the default account.

**Comment by joroshiba** [comment]
We should look into using [helm charts](https://helm.sh/docs/chart_template_guide/getting_started/) to create a configurable EVM, it should allow the EVM to be run both with custom funding account AND with different chain ids.
