### ISSUE TITLE
Generate test data in EVM

### ISSUE THREAD

**Issue by jbowen93** [astriaorg/dev-cluster#21]
We need a way to generate test data in the EVM so that indexers can check if their system is working. 

Possible options to look into:
- https://github.com/paradigmxyz/flood
- https://github.com/ethereum/eth-tester
- https://github.com/ethereum/tests
- https://github.com/ethereum/hive (see: https://github.com/astriaorg/dev-cluster/issues/3)

**Comment by joroshiba** [comment]
There are three different problems to be solved here, in order of importance to us:

1. Getting some test data in to provide transaction data which can be used to validate indexing is working
2. Validating EVM against EVM conformance tools
3. Performance testing of the EVM

For number 1 I think the following tools may be useful:

- [Eth Tester ](https://github.com/ethereum/eth-tester)
- [Polaris erc20 foundry script](https://github.com/berachain/polaris/blob/main/contracts/scripts/DeployAndCallERC20.sol)

For the second:

- [Ethereum tests](https://github.com/ethereum/tests) - some testing tools for EVM
- [Hive](https://github.com/ethereum/hive) - note this tech stack doesn't work neatly with a modular setup.

For the third take a look at [flood](https://github.com/paradigmxyz/flood), although it's possible flood could be used to generate chain data as well.

Our initial goal should be simply solving part 1

**Comment by steezeburger** [comment]
@sambukowski I created a [web3 monorepo](https://github.com/astriaorg/astria-web3) that would be a good place to put this work

**Comment by sambukowski** [comment]
Got this done using Forge scripts.
