### ISSUE TITLE
Persistant storage for chains

### ISSUE THREAD

**Issue by joroshiba** [astriaorg/dev-cluster#27]
On reboot, all of our pods lose their chain information. Need to update to have options for persistent storage, required for a public devnet.

**Comment by steezeburger** [comment]
https://kubernetes.io/docs/concepts/storage/dynamic-provisioning/
https://kubernetes.io/docs/concepts/storage/persistent-volumes/
https://kubernetes.io/docs/concepts/storage/storage-classes/
https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/

https://cloud.google.com/kubernetes-engine/docs/concepts/persistent-volumes

**Comment by steezeburger** [comment]
Geth, CometBFT, Sequencer still need persistent storage
