### ISSUE TITLE
Document where block scout can be found

### ISSUE THREAD

**Issue by jbowen93** [astriaorg/dev-cluster#77]
In the Readme we note where to find the faucet for a given rollup (https://github.com/astriaorg/dev-cluster#faucet) but we do not say where the block explorer for a rollup is.

It looks like this is at:
```
blockscout.<rollup name>.localdev.me
```

**Comment by jbowen93** [comment]
Related to this, it looks like we aren't producing empty blocks. So the block explorer will look like it's paused if the end user isn't submitting transactions. 

We should note this up front.

**Comment by jbowen93** [comment]
One more point, and this relates to both the faucet and block explorer. I'd like to have links that open the default in a new tab. Ideally it's a single click for a user to see that things "just work". 

This would be:
- http://blockscout.astria.localdev.me
- http://faucet.astria.localdev.me

**Comment by steezeburger** [comment]
Note that new tab may not be possible in gh markdown https://stackoverflow.com/a/42156438
